# Generated by Django 3.0.4 on 2020-04-08 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventCalendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('calendarID', models.AutoField(primary_key=True, serialize=False)),
                ('calendarName', models.CharField(blank=True, max_length=255, null=True)),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='getCalendar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
