# Generated by Django 3.0.4 on 2020-04-08 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventCalendar', '0002_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('meetingID', models.AutoField(primary_key=True, serialize=False)),
                ('invitedUserID', models.IntegerField(null=True)),
                ('sentCalendarID', models.IntegerField(null=True)),
                ('awr', models.CharField(blank=True, max_length=255, null=True)),
                ('acceptedCalendarID', models.IntegerField(null=True)),
                ('computedStart', models.DateTimeField(null=True)),
                ('computedEnd', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='calendarID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventCalendar.Calendar'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='userID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
