# Generated by Django 3.0.4 on 2020-04-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventCalendar', '0007_auto_20200415_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetings',
            name='acceptedCalendarID',
        ),
        migrations.RemoveField(
            model_name='meetings',
            name='invitedUserID',
        ),
        migrations.RemoveField(
            model_name='meetings',
            name='sentCalendarID',
        ),
        migrations.AddField(
            model_name='meetings',
            name='invitedUsername',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
