# Generated by Django 3.0.4 on 2020-04-15 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventCalendar', '0008_auto_20200415_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetings',
            old_name='awr',
            new_name='attendance',
        ),
        migrations.RemoveField(
            model_name='meetings',
            name='computedEnd',
        ),
        migrations.RemoveField(
            model_name='meetings',
            name='computedStart',
        ),
        migrations.RemoveField(
            model_name='meetings',
            name='invitedUsername',
        ),
        migrations.AddField(
            model_name='meetings',
            name='beginLimit',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='meetings',
            name='endLimit',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='meetings',
            name='meetingDuration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meetings',
            name='meetingName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meetings',
            name='partUsername',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Meetings_Computed',
            fields=[
                ('meetingCompID', models.AutoField(primary_key=True, serialize=False)),
                ('computedStart', models.DateTimeField(null=True)),
                ('computedEnd', models.DateTimeField(null=True)),
                ('meetingID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventCalendar.Meetings')),
            ],
        ),
    ]
