# Generated by Django 3.0.4 on 2020-04-15 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventCalendar', '0009_auto_20200415_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetings',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='meetings',
            name='partUsername',
        ),
    ]
