# Generated by Django 3.0.4 on 2020-04-15 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventCalendar', '0011_meetings_creatorusername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetings',
            old_name='creatorUsername',
            new_name='creatorID',
        ),
    ]
