# Generated by Django 3.0.4 on 2020-04-15 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventCalendar', '0012_auto_20200415_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetings',
            name='beginLimit',
        ),
        migrations.RemoveField(
            model_name='meetings',
            name='creatorID',
        ),
        migrations.RemoveField(
            model_name='meetings',
            name='endLimit',
        ),
        migrations.RemoveField(
            model_name='meetings',
            name='meetingDuration',
        ),
        migrations.RemoveField(
            model_name='meetings',
            name='meetingName',
        ),
        migrations.RemoveField(
            model_name='meetings_computed',
            name='computedEnd',
        ),
        migrations.RemoveField(
            model_name='meetings_computed',
            name='computedStart',
        ),
        migrations.RemoveField(
            model_name='meetings_computed',
            name='meetingID',
        ),
    ]
