# Generated by Django 3.0.4 on 2020-04-15 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventCalendar', '0013_auto_20200415_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='beginLimit',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='meetings',
            name='creatorID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetings',
            name='endLimit',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='meetings',
            name='meetingDuration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meetings',
            name='meetingName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meetings_computed',
            name='computedEnd',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='meetings_computed',
            name='computedStart',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='meetings_computed',
            name='meetingID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventCalendar.Meetings'),
        ),
        migrations.AddField(
            model_name='meetings_computed',
            name='meetingIsActive',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MeetingParticipation',
            fields=[
                ('meetingParID', models.AutoField(primary_key=True, serialize=False)),
                ('partUsername', models.CharField(blank=True, max_length=255, null=True)),
                ('attendance', models.BooleanField(default=False)),
                ('meetingID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventCalendar.Meetings')),
            ],
        ),
    ]
