# Generated by Django 3.0.4 on 2020-04-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventCalendar', '0014_auto_20200415_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='beginLimit',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='endLimit',
            field=models.TimeField(null=True),
        ),
    ]
