# Generated by Django 3.0.4 on 2020-04-29 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventCalendar', '0016_auto_20200422_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='invitedMeetingList',
            fields=[
                ('invitedMeetingID', models.AutoField(primary_key=True, serialize=False)),
                ('participantID', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingEvents',
            fields=[
                ('meetingEventID', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('voteNumber', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='meetings',
            name='beginLimit',
        ),
        migrations.RemoveField(
            model_name='meetings',
            name='endLimit',
        ),
        migrations.RemoveField(
            model_name='meetings',
            name='meetingDuration',
        ),
        migrations.AddField(
            model_name='meetingparticipation',
            name='is_voted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetingparticipation',
            name='partID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='meetings',
            name='is_decided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetings',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meetings',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meetings',
            name='participants',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meetings',
            name='recurrence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Meetings_Computed',
        ),
        migrations.AddField(
            model_name='meetingevents',
            name='meetingID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventCalendar.Meetings'),
        ),
        migrations.AddField(
            model_name='invitedmeetinglist',
            name='meetingID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventCalendar.Meetings'),
        ),
    ]
