# Generated by Django 3.0.4 on 2020-05-05 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventCalendar', '0017_auto_20200429_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingparticipation',
            name='attendance',
        ),
        migrations.AddField(
            model_name='meetingparticipation',
            name='meetingEventID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventCalendar.MeetingEvents'),
        ),
    ]
