# Generated by Django 3.0.4 on 2020-05-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventCalendar', '0018_auto_20200505_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetings',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
