# Generated by Django 3.0.4 on 2020-06-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventCalendar', '0020_auto_20200601_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='recurrence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
