# Generated by Django 3.0.4 on 2020-06-02 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventCalendar', '0022_remove_events_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='meetingID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventCalendar.Meetings'),
        ),
    ]
